/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Status { 
    /**
     * Estado en la que acaba la llamada
     */
    status?: number;
    /**
     * Mensaje que describe el estatus que se ha puesto
     */
    message?: string;
}